# Import Library

In [ ]:
# Install Biopython package
!pip install biopython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting biopython
  Downloading biopython-1.81-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 30.4 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from biopython) (1.22.4)
Installing collected packages: biopython
Successfully installed biopython-1.81

In [ ]:
from google.colab import drive
from Bio import SeqIO
import pandas as pd
import numpy as np
import re

# Load Data

In [ ]:
file_path = '/content/gdrive/MyDrive/Colab Notebooks/Dataset/DM5.fas'
drive.mount('/content/gdrive')

with open(file_path, 'r') as f:
    file_str = f.read()

# Split the file string into individual sequence records
records = file_str.split('>')

# Remove empty strings
records = [rec for rec in records if len(rec) > 0]

records

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

['JP 2014097060-A/44: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/44: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nACACATATTTTAATTAAATAGCTTCATATTTAGCTTCAAGAAGATGAGTACTGGCCATATATTTGAATATATATGCTATATTAGTTTAAATCTCATGTCAGATGATTTGCAGGTCTTTTTATTTGCATGTTTATGCAGCTAAGATGTTTGGCGCTCAGTTCTTGTGGGAGGGGGCAGCTTGGTATGGAAAGAACTTGGAGTTTGAAATCTCACTGTCCTGGATTTGAATCTCAGCTGTTACATGGCCTTGAGCAGGCTACTTATCTGATTTTTTGAGGTGGATTCTTGTCTGTAAGATCRAGATAGGGAAACCCAACTCTGAAAGGGTTAAATGAGATAAGGCATATAAAATATCAGTAACAGGCTCACTGGCTCACACCTGTAATCCCAGCACTTTGGGAGGCCGAGAGGGGAGGGTCGCTTGAGCCCAGGAGTTTGAGACCAACCTGGGCAACATAGCGAGACCCCGTTTCTATTAAAAAAAAAAAGAAACAGAAAAACAAAAACAAAAAAAAGAAAATATCGACAACAGTGTCTGATGCTCAGTAAGGGCTAAACAAAATTGAGTTACTCTACCAAGGAAACGACAATAGAATGGT------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/43: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/43: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nAAAAAAAAAGATAAACACTTTTACCTCTAGTAACTGATCACAACAAAGCTGCCATTTCATACCATGGGAGACTCCATGGTTATCCAGAATCAAAGGTCTTTCATTCCCTGCCCTCTTGCCAAGCCACATTTCAGGAGTCAGCATTGTTCTAATGGATGCCATTTGTCTTTACACTATCTGAAGTGAGCCAGACTTCAAGGTTTGAGAGCACAGTCTCCCAGACTGCAAAGTTTGCCCAAGCCTCTGATACTCCCTGCAAGGAGGTCCCACAAGGTTAGGGGGCATGGTTTTAGGACTTCYGTCACCTCTGACCTAACTGCAAGTTCAGGAAGTTTCCAAAACGACCTTCAGGTTCAAAAATTCACTAAAAAGAATCACAGAACTCTTTGAAAGCTGTTATACTCACAGTTACAGTTTATTTCAGGGAAAGGATAGAGATCAAAATTAGCCAAAGAAAGAGATTGATAGAGCAGAGTCTGAGAGGGTTCCAAATGTGAAGCCTCTGGGGTCCTCAGAATGCATTACCCTGCTGATTTGGATGTGTGAGACAACACATATAGAGTACTGCCAATCAGGGACACTCACCTGAGCTTCAGCAT------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/42: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/42: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nGGAGAATAAATGGCACCATGCAGGAACAAGGAAGAGAAGTGGACATGCATTTTTTTTCTGTTTTTTTTTTTCTTTTTGAGACGGAGTCTCGCTCTGTCGCCAGGTTGGAGTGCAGTGGCACCATCTCTGCTCACTGCAACCTCTGCCTCCCAGGTTCAAGCAATTCTCCCGCCTCAGCCTCCTGAGTAGCTGGGATTACAAGCATGTGCCACCATGCCCAGCTAATTTTTGTATTTTTAGTAGAGATGGAGTTTCGCCACGTTGGCCAGGATTGTCTCGACCTCTTGACCTTGTGATTCRCTTGCCTTGGCATTTATTGATCCATTTATAAACTATTGACCTTGTAAGAATGTCTACAGCAGAGTGTTTAATTTGTATGTCTATTCATTAAAACTCCTTTGATTGATAGTTAATTGGTTTATAATATTAGTTTCAAGACTAAACAAGCTGTGTATGTAACATTTGATCTTTCAGTTACAGGCTTTATCACAAAAAAGTAATGCTGTATCTCTTTTTCCTGGATTTTTATCCACCTGAAATTTCTGATGTCCACAATGGTCCCACCTGGCTATCTACTTTCTGCACATATTTTCACGTGT------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/41: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/41: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nTATATATTTACAGGGCACATGAGGTGTTTCGATACAGGCCTCCAGTGCATAATAATCACATCATCGAGAATGGAATATCCATTCCCTTGTGCATCTATCCTTTGTGTTACAAATAATTCAATTACACTGTTTAAGTTGCTTTAAAATGGGCAATTTTTATTGACTATAGTTATCCTGCTGTGCTATCAGATAGTAAGTCTTATTTATTCTTTCTGTGTTTTTTGTACCCATTAACTATCCCCACCTTCCCCCAACACCACACTATGCTTCCAAACCTCTGGTAAACATCCTTCTACCTAYGTTCATGAGTTCAATTGTTTTGATTTTGAGATCTCACAAATTAGTAAGAACATGCAATGTTTATCTTTCTGTGCCTGGTTTATTTCACTTAACACAATGACCTCCACTTTCATGCATGTTGTTGCAAGTGACAGGACCTCATTCATTTTTATGGCTGAATAGTACTCCATTATGTCTATGTACCACATTTTCTTTATCCATTCATCTGTTGATGAACACATAGGTTGCTTCCAAACCTTAGGTATGGTGAACAGTGCTGCAACAAACATAGGAGTGCAGATATCTCTTTGATGTACTGA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/40: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/40: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nGATGGGGACTTTGCCAAATTGAGAGCTCCCGTTAGTTTTTCTTCTTGGTTTTATGAGCCCATGACCCATCTTGATTCTTTCTTGCCTGATGAGGTTTTGATAGACTATAGATTGGCTTACCTGACCTAGAAACTTGTGATTTTTACTCTGGTAGATATCCATACCAACCTAAGGGGCCTAAATCCATGCCAACCCTTGATGCCCTGATACTGGATCCTACATAAAAAGAGAGTTTGAACCCAGTATTTCTAAGATCCTGATGTTTCAAAAACAATGCTACTTTATCTTATGAATCATTTRTCACTTGCTCCTTCAGGCAGGTAAATATAATGAGGCTGACAGCAGCCAAGGCCATGCTGCTCATCATACACAATCATGTCAACCTGCTGTGAAAGTCTGTGCCATTTTCCCTCCATCACATCTGTCTTGTTCTCTTTGCCGAAAGCTGAGTTACTACATCTTGGCTGATTCAGAATTTTGTCTAGTTCTTTCCTTACAGGTTCCCCATTGTCTCTTTGATACTATTTTATACCTAAAATTCCTCTCTATTTGTTTAATGCAAATCAGAAACCTAAGGCAAGGGACAGCTGGTCACCAAA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/39: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/39: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nGCTCAGCCTCCTGAGTAGCTGACAACCGCAGGCACACACCACCATGCCCAACTAATTTTTGTCCTGGCTACTTTTACTCCTAAACCTTCTCCTTCTCCATAAACATCATATTTTTCATAACTTCTCCCCTTCCACTCTTTATACCAGCAAGACGAATGTTGCCCCAGTGGCCAAATATGTGTTATTTCACATTGCCCTGCTCTAATTAAGGAGGTGTGAAGAAGGAAATGCTAGCAACAGCAATGATAACTCAGGTGGCTTTGTGTGTGTGTTCTGGGAGTGGAGTGTCTTTAAGTGAGMATATTGGAGCACAGGATAGACAGGAAGAGCTCCAGTGTTAGTAAAATTATGAATCATTACTATGTTGGGGACTTCTAGAATTTAGGTCCAAAACAATTCTCCTGTGGTTGCAATCCATTATAAGTCATTCAATTAATAAAGAATGAACCAATTAATGGAAATAATATAAACCATAGACTTCTGAAAAAGTGGTAAGGATTTTTGAAATATATCCTAATGTGCACCAGGAGTCAAGTAACATGGACAGAGTATTTACTCAGCACATAAGTTGTTAGGCACAGATTATTAAGACTAAAGAA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/38: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/38: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nTTAGCAGCAGAATTACAAGAAATCTTGGGACCTGTAGTCTTAATTCAAGATAAGGCCATGGGGCCTGAGGCACCCCTAGACCCTGAGCCTTCACCGTTAGGATGGGCATCCCCCCGTTCCTAATAGGGTATGGTATACAGATAGGTCTAGCCGGGGTGCTTCTGCTGCCTGACTGTTGTTGCAGCCCAGCCTAGTACTAACACCATATGGTATGAAACCAGGTGTAAACAGAGTAGCTAATGAGCTAACTCAGGGCAGTGTGAATAATAACCACCAAAAGGGTGACACCTGTGGTAATCYGCACCAATAGCTGGGCAGTTTATCGAGGCTTATGTATGTCATGGGCCTGTGTGCCTAAAGCCTACGTGTCAAGCTACTGTGTCAAGCCTGTGTGTGTATATCTGGCCTGTATGCCCAAAGCCTACGGTCAGGCTAATGTGTGTCAAACCTGTGTATCCAAAACCTACGTCTCCCTCGGCCTGGGGGGGTGGAGTGTAAGGCATATGGACGTGCTTTGGTCAAGGAATAGGCTGAGGTGGATATCCAGGCCTGCATGAGTCCAGCGAGTTTGGTGTGCAGGCGCACACCTCCACTTGTTA------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/37: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/37: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nTGTAGATGGTTAATATCCAAAAAACAAAAAGGAAAAAAAAACCCAACTCTTTTATGTGCTCTAATGTATTTGCTGTTGAAAACAAAGGGAATTTGTGATTCATTTAAAAAATATATATATAGCTATTTGATGATTTTGAAGATATTTTATAGTTATTGTTCCATTTGAATGAAGTAAAAATGTTATGATGTCTTAGGGTACAATTGAGCTATAATTTTAGTATGTCAATGACTACAGCTTTTTTCTAGGGAAGGTTATAATAGTTAACAGGAAAATATGACATAAATAGTAAAAACATGRTATAATAGTAAAAATTAGTAAAAAATTTTTGTTTTGGGCTGTAAGTTTTTTTGGAGAGGAGACTGTAGTAAGTGTAAAAACATGATGTTATATAATTAGTTTTACACATATTTTCAGGAATATTTTTAATACACAAATGTGTGGATATAGTCTATTTTGGTGTGAATTTAAACTTTGAAAACTGCTAAAAGTTTCAGTTACTTGAGAAATAGTGAATTTTTATTTAATGATCAAATTAAACACTAATAAAATTATGTCTTTATTGTTTTCAGTTTTGAGAGCATTTGAAAAGTGCAGGC------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',
 'JP 2014097060-A/36: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DEFINITION JP 2014097060-A/36: GENETIC SUSCEPTIBILITY VARIANTS OF TYPE 2 DIABETES MELLITUS.\nCTGGAGTGCATGGTCACAGCTCACTGCAGCCTCGACCTCCTAGGCACGGGTGATCCTCCTGAGTAACTGGGACTGTAGGCACTCACCACCACATGCAGCTAATTTTTCTATTTTTGGTAGAGAGGGGATTTTGCCATGTTGCCCAGGCTGGTCTTGAGCTCCTGGGCTCAAGTGATCTGTCTGCCTCTGCCTACCATAGTGCTAGGATTATAGGCATGAGCCACCTTGCCCTGCTTCTTTCTCTAGATCCAAATTTCTGACCTACATCATTTTTATCCTATGTAAAGGATTTTTTTTTTWAATTTCTTGCAAGGTAGATCTACTGGCAAAAAAATCTCTCAATTTTTGTTTGTTTGAGAAAGTATTTTTCCTTCACTTTTGAAGAATGATTTTGCGGGTTACAGAATTCTATGTTGTTGTTTTTTCTTTTTTTTTATCAACACTTTATTTTACTTTACCACTCGCTTGTATGGTTTCTAGCAGAAGTAAAATGTAATTCTTATCTTTGCTTCTGTCTAGCTAAGGGTTATTCCCCCCTCACCCCCCACCTCTGGCTTCTTTCAGGTTTTTTTCTTTATCTTTGACTTTCTGTAGTTTGC------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n',

In [ ]:
# Split each record into its ID and sequence
df_list = []
for rec in records:
    rec_split = rec.split('\n')
    seq_id = rec_split[0]
    sequence = ''.join(rec_split[1:])
    df_list.append({'id': seq_id, 'sequence': sequence})

# Create a Pandas DataFrame from the list of sequence records
df = pd.DataFrame(df_list)

df

,id,sequence
0,JP 2014097060-A/44: GENETIC SUSCEPTIBILITY VAR...,ACACATATTTTAATTAAATAGCTTCATATTTAGCTTCAAGAAGATG...
1,JP 2014097060-A/43: GENETIC SUSCEPTIBILITY VAR...,AAAAAAAAAGATAAACACTTTTACCTCTAGTAACTGATCACAACAA...
2,JP 2014097060-A/42: GENETIC SUSCEPTIBILITY VAR...,GGAGAATAAATGGCACCATGCAGGAACAAGGAAGAGAAGTGGACAT...
3,JP 2014097060-A/41: GENETIC SUSCEPTIBILITY VAR...,TATATATTTACAGGGCACATGAGGTGTTTCGATACAGGCCTCCAGT...
4,JP 2014097060-A/40: GENETIC SUSCEPTIBILITY VAR...,GATGGGGACTTTGCCAAATTGAGAGCTCCCGTTAGTTTTTCTTCTT...
...,...,...
405,Sequence 1 from Patent WO03060130. DEFINITION ...,GAGGGCCGTCGCCCGCGATGCTGCTCTCCAAGTTCGGCTCCCTGGC...
406,Sequence 371 from Patent WO2008065544. DEFINIT...,TTAGCAGCTACTGAAAATATATAAGTAATTTATGGCTACACTTCAA...
407,Sequence 240 from Patent WO2008065544. DEFINIT...,AAAAAAAAATTGAATCCAGTGGGGAACTCAATCTTAGTAAACTACA...
408,Sequence 24 from Patent WO2008065544. DEFINITI...,TCTACAGATGCTTTTGGATTTGCTAGGTAGACAATCATGTGCAAAT...
409,Sequence 22 from Patent WO2008065544. DEFINITI...,ATGGTAAACTTGCTAACTTCATCTACAGATGCTTTTGGATTTGCTA...

In [ ]:
new_column = pd.Series([1] * 410)

df['class'] = new_column

df = df.drop('id', axis=1)

In [ ]:
df

                                              sequence  class
0    ACACATATTTTAATTAAATAGCTTCATATTTAGCTTCAAGAAGATG...      1
1    AAAAAAAAAGATAAACACTTTTACCTCTAGTAACTGATCACAACAA...      1
2    GGAGAATAAATGGCACCATGCAGGAACAAGGAAGAGAAGTGGACAT...      1
3    TATATATTTACAGGGCACATGAGGTGTTTCGATACAGGCCTCCAGT...      1
4    GATGGGGACTTTGCCAAATTGAGAGCTCCCGTTAGTTTTTCTTCTT...      1
..                                                 ...    ...
405  GAGGGCCGTCGCCCGCGATGCTGCTCTCCAAGTTCGGCTCCCTGGC...      1
406  TTAGCAGCTACTGAAAATATATAAGTAATTTATGGCTACACTTCAA...      1
407  AAAAAAAAATTGAATCCAGTGGGGAACTCAATCTTAGTAAACTACA...      1
408  TCTACAGATGCTTTTGGATTTGCTAGGTAGACAATCATGTGCAAAT...      1
409  ATGGTAAACTTGCTAACTTCATCTACAGATGCTTTTGGATTTGCTA...      1

[410 rows x 2 columns]

## Cek selain A, C, G, T

In [ ]:
invalid_chars = []
for sequence in df['sequence']:
    invalid = ''.join(set(sequence.upper()) - set('ACGT'))
    if invalid:
        invalid_chars.append(invalid)

# Display the erroneous characters or punctuation marks
if invalid_chars:
    print("Invalid characters or punctuation marks found:")
    for invalid in invalid_chars:
        print(invalid)
else:
    print("No invalid characters or punctuation marks found.")

Invalid characters or punctuation marks found:
-R
Y-
-R
Y-
-R
-M
Y-
-R
W-
-M
Y-
-R
-R
-M
-M
-R
-R
Y-
Y-
-R
-R
-R
-R
-R
-R
Y-
-R
-R
-M
-R
-R
-R
Y-
Y-
-R
-S
-R
Y-
Y-
Y-
-R
-R
Y-
-R
Y-
-R
-M
Y-
-R
W-
-M
Y-
-M
-R
-R
-R
Y-
Y-
Y-
-R
-R
-R
-R
-R
-R
Y-
-R
-R
-M
-R
-R
Y-
-R
Y-
Y-
-R
-S
-R
Y-
-S
-S
-
-M
W-
-R
-M
Y-
-R
-S
Y-
W-
Y-
Y-
K-
-
-
-
-
-
-
-
-
-R
-S
W-
Y-
-S
Y-
-R
Y-
-R
-R
Y-
-M
-R
-R
Y-
-R
-R
Y-
-R
-R
Y-
-R
W-
Y-
Y-
-R
K-
-R
-D
Y-
-R
K-
K-
W-
-S
-R
-R
Y-
Y-
Y-
Y-
-R
K-
Y-
-R
-S
W-
Y-
-S
-R
Y-
-M
Y-
Y-
K-
-R
-R
-S
Y-
Y-
Y-
Y-
-R
Y-
Y-
K-
-R
-S
-R
-S
-M
-R
Y-
Y-
Y-
W-
-R
-R
Y-
-R
-R
-M
Y-
Y-N
Y-
Y-
-S
-R
K-
-R
-S
-R
-R
-S
Y-
-R
W-
Y-
W-
Y-
-R
W-
-R
-S
-M
K-
-M
-R
-R
-R
-M
Y-
W-
Y-
Y-
-R
Y-
Y-
Y-
-R
-R
-R
Y-
Y-
-M
-S
-R
-R
-M
-S
Y-
Y-
Y-
-R
W-
-R
Y-
Y-
K-
-R
W-
-R
-M
K-
Y-
-R
Y-
Y-
-M
Y-
Y-
K-
Y-
-R
-M
Y-
-R
-R
-M
Y-
W-
-R
K-
K-
Y-
-M
-R
-R
Y-
-S
-S
W-
-R
Y-
W-
-R
-S
K-
-R
K-
Y-
Y-
-R
-M
Y-
Y-
-R
Y-
-M
Y-
-R
Y-
-R
Y-
Y-
-R
-R
-R
Y-
-R
Y-
Y-
Y-
Y-
-R
-R
Y-
-R
-M
-R
-R
-R
-R
-S
K-
-R
-M
Y-
K-
-R
W-
K-
-R
-R
Y-
-R
Y-
Y-
-R
W-
K-
K-
-R
-S
Y-
-R
-R
W-
Y-
Y-
-M
K-
-R
-R
-R
K-
Y-
Y-
-R
-M
K-
Y-
-R
-R
-R
-R
Y-
K-
-M
-R
Y-
Y-
-R
Y-
-R
Y-
-S
-S
Y-
Y-
-M
Y-
Y-
K-
-R
-R
-R
K-
-R
-R
-M
Y-
Y-
Y-
-S
-M
-S
Y-
-R
-M
Y-
-R
-R
-M
K-
K-
-M
-R
-R
Y-
-R
Y-
Y-
-R
W-
-R
-R

# Preprocessing

## Bersihkan selain A, C, G, T

In [ ]:
# Function to preprocess DNA sequence
def preprocess_sequence(sequence):
    # Remove invalid characters
    processed_sequence = re.sub('[^ACGT]', '', sequence)
    return processed_sequence

# Preprocess the 'Sequence' column
df['sequence'] = df['sequence'].apply(preprocess_sequence)

# Print the updated dataframe
df

                                              sequence  class
0    ACACATATTTTAATTAAATAGCTTCATATTTAGCTTCAAGAAGATG...      1
1    AAAAAAAAAGATAAACACTTTTACCTCTAGTAACTGATCACAACAA...      1
2    GGAGAATAAATGGCACCATGCAGGAACAAGGAAGAGAAGTGGACAT...      1
3    TATATATTTACAGGGCACATGAGGTGTTTCGATACAGGCCTCCAGT...      1
4    GATGGGGACTTTGCCAAATTGAGAGCTCCCGTTAGTTTTTCTTCTT...      1
..                                                 ...    ...
405  GAGGGCCGTCGCCCGCGATGCTGCTCTCCAAGTTCGGCTCCCTGGC...      1
406  TTAGCAGCTACTGAAAATATATAAGTAATTTATGGCTACACTTCAA...      1
407  AAAAAAAAATTGAATCCAGTGGGGAACTCAATCTTAGTAAACTACA...      1
408  TCTACAGATGCTTTTGGATTTGCTAGGTAGACAATCATGTGCAAAT...      1
409  ATGGTAAACTTGCTAACTTCATCTACAGATGCTTTTGGATTTGCTA...      1

[410 rows x 2 columns]

## Gabungkan 2 data

In [ ]:
df.to_csv('DIAM2.csv', index=False)

In [ ]:
import pandas as pd

# Read the first dataframe from CSV
df1 = pd.read_csv('DIAM1.csv')

# Read the second dataframe from CSV
df2 = pd.read_csv('DIAM2.csv')

# Combine the dataframes
combined_df = pd.concat([df1, df2], axis=0)

# Reset the index
combined_df.reset_index(drop=True, inplace=True)

# Save the combined dataframe to a new CSV file

In [ ]:
combined_df.to_excel('dataset.xlsx', index=False)